Remove trailing empty lines on checklist import
apps4av/avarex pull request #20
Opened 2024-09-08 07:03 UTC by no-lex

Resolves a minor oversight I found where upon importation of a checklist, trailing empty lines will get their own checklist entry. This change removes those empty trailing entries during the loading process.

I decided not to remove empty lines surrounded by text, since those could have some use as a spacer. (It may be worth keeping the spaces they create while removing their corresponding checkbox)

![Screenshot from 2024-09-07 23-47-17](https://github.com/user-attachments/assets/e23eb19a-e69a-4cbe-9080-728e7afac507)

2024-09-09 21:04 UTC, apps4av requested changes

2024-09-09 21:04 UTC, apps4av commented on lib/checklist_screen.dart
> +          while(!lines.isEmpty)
use isNotEmpty

2024-09-09 21:04 UTC, apps4av commented on lib/checklist_screen.dart
> +            if(lines[lines.length - 1].length == 0) {
use isEmpty

2024-09-09 21:04 UTC, apps4av commented on lib/checklist_screen.dart
> +            }
I suggest running a for loop here instead of while to make it more readable.

2024-09-13 13:33 UTC, apps4av commented on lib/checklist_screen.dart
> +          //remove trailing empty lines, back to front, until no lines remain or
I see you are removing trailing empty lines, why not remove leading empty lines as well?

2024-09-14 14:48 UTC, apps4av reviewed
Now I think more about it, why not remove all empty lines? Empty line may be used for spacing steps but its not a step. Going forward, clicking all steps will move to the next checklist. If some empty lines remain, then use has to check them too, which makes no sense.

2024-09-14 17:17 UTC, no-lex commented
My thought was that those intermediate empty lines would remain but that the check tick itself would be disabled, which I was thinking of targeting in a separate PR. If this is infeasible though, I can just delete all empty lines.

2024-09-25 18:26 UTC, apps4av approved these changes

2024-09-25 18:27 UTC, apps4av commented
For concise code, use map() function instead. These 20 lines could be condensed into 2 line. Approved.

2024-09-25 18:35 UTC, merged